
Epoch 1/30
INFO:tensorflow:Error reported to Coordinator:
Traceback (most recent call last):
  File "/home/paperspace/Documents/tensor_env/lib/python3.9/site-packages/tensorflow/python/training/coordinator.py", line 293, in stop_on_exception
    yield
  File "/home/paperspace/Documents/tensor_env/lib/python3.9/site-packages/tensorflow/python/distribute/mirrored_run.py", line 225, in _call_for_each_replica
    t.has_paused.wait()
  File "/usr/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt